package com.joaonf.mellifera.client;

/// Where the moving parts of each machine window go.
///
/// GENERATED by tools/gen_machine_guis.py from the same table that paints the backgrounds. Do not
/// edit by hand: the numbers here are the insides of housings painted into the PNGs, and a screen
/// filling a rectangle the art does not have is exactly the mismatch this file exists to prevent.
///
/// Slot positions are *not* here. Those live in the menus, they are gameplay rather than decoration,
/// and the painted wells are fitted around them rather than the other way round.
public final class MachineGeometry {
    private MachineGeometry() {}

    /// A rectangle in window space: x and y from the window's top-left corner, then its size.
    public record Rect(int x, int y, int width, int height) {}

    /// The raised rectangle every window is built inside. The energy column bolts itself to
    /// the window's left edge across exactly these rows, so the two line up without either
    /// knowing the other's numbers.
    public static final Rect FRAME = new Rect(11, 18, 154, 59);

    // -- centrifuge
    public static final Rect CENTRIFUGE_TRACK = new Rect(53, 46, 30, 3);

    // -- squeezer
    public static final Rect SQUEEZER_TRACK = new Rect(53, 46, 30, 3);
    public static final Rect SQUEEZER_TANK = new Rect(113, 25, 26, 45);

    // -- isolator
    public static final Rect ISOLATOR_TRACK = new Rect(47, 46, 30, 3);

    // -- infuser
    public static final Rect INFUSER_TRACK = new Rect(47, 46, 30, 3);

    // -- carpenter
    public static final Rect CARPENTER_TRACK = new Rect(51, 46, 30, 3);
    public static final Rect CARPENTER_TANK = new Rect(125, 25, 26, 45);

    // -- engine
    public static final Rect ENGINE_TRACK = new Rect(53, 46, 30, 3);
    public static final Rect ENGINE_TANK = new Rect(113, 25, 26, 45);
}
