"""Generates the two Apiary models that grow a stand: apiary_stand and apiary_bottom_stand.

    python tools/gen_apiary_stand_models.py src/main/resources/assets/mellifera/models/block

Not part of the Gradle build, and kept for the same reason as the texture generators: the two
files it writes are three hundred lines of coordinates each, and the only readable statement of
what they are is this one -- scaffolding's own shape, one block lower, in the hive's timber.

A hive on scaffolding should look like it is standing on a trestle, not like it is standing on
scaffolding with a trestle next to it. So the Apiary draws scaffolding's geometry itself, in its
own boards, a hair outside the real thing, and what the player sees is the mod's wood instead of
the vanilla texture. The scaffolding block is untouched: still climbable, still breakable, still
scaffolding to every other part of the game.

Two things about the copy are worth knowing before changing it.

SKIN cannot be zero. Two identical coplanar faces fight, and which one wins is whatever the
depth buffer feels like that frame. One hundredth of a unit is the same margin vanilla itself
uses when it wants a surface to win -- scaffolding's own deck is 15.99 rather than 16 for
exactly this reason -- and at 1/1600 of a block it is far below anything a player can see.

The geometry copied is the *stable* model, which is the one with no bottom deck. Copying the
unstable one drew a deck and a set of bottom rails under hives whose scaffolding has neither,
which is worse than drawing nothing: it invents structure that is not there.
"""
import json
import sys

# Lifted from assets/minecraft/models/block/scaffolding_stable.json: the deck at the top, four
# corner posts down the full height, and four rails joining their heads. Written out here rather
# than read from the client jar so this script stands on its own.
SCAFFOLDING_STABLE = [
    ([0, 15.99, 0], [16, 16, 16], ["down", "up"]),
    ([0, 0, 0], [2, 16, 2], ["down", "north", "south", "west", "east"]),
    ([0, 0, 14], [2, 16, 16], ["down", "north", "south", "west", "east"]),
    ([14, 0, 14], [16, 16, 16], ["down", "north", "south", "west", "east"]),
    ([14, 0, 0], [16, 16, 2], ["down", "north", "south", "west", "east"]),
    ([2, 14, 0], [14, 16, 2], ["down", "north", "south"]),
    ([2, 14, 14], [14, 16, 16], ["down", "north", "south"]),
    ([14, 14, 2], [16, 16, 14], ["down", "west", "east"]),
    ([0, 14, 2], [2, 16, 14], ["down", "west", "east"]),
]

SKIN = 0.01     # see the note above: enough to win the depth test, far too little to see
DROP = -16.0    # scaffolding's block is the one under the hive
FLOOR = -16.0   # a model element may not reach below this
CEILING = 0.0   # nor is there any reason to reach above the hive's own floor

POST = "#post"          # mellifera:block/apiary_stand -- plain upright boards
BODY = "minecraft:block/block"


def convert(from_, to, faces):
    (x0, y0, z0), (x1, y1, z1) = from_, to

    out = {}
    for name in faces:
        if name == "up" and y1 == 16:
            continue  # would be coplanar with the hive's own floor, and never visible anyway

        # v runs down from the top of the texture. Taking it from scaffolding's own coordinates
        # rather than from the dropped ones keeps the boards at the density the real block has.
        if name in ("north", "south"):
            uv = [x0, 16 - y1, x1, 16 - y0]
        elif name in ("west", "east"):
            uv = [z0, 16 - y1, z1, 16 - y0]
        else:
            uv = [x0, z0, x1, z1]

        out[name] = {"uv": [round(v, 2) for v in uv], "texture": POST, "tintindex": 0}

    return {
        "from": [round(x0 - SKIN, 2), round(max(y0 + DROP - SKIN, FLOOR), 2), round(z0 - SKIN, 2)],
        "to": [round(x1 + SKIN, 2), round(min(y1 + DROP + SKIN, CEILING), 2), round(z1 + SKIN, 2)],
        "faces": out,
    }


STAND = [convert(*element) for element in SCAFFOLDING_STABLE]

NOTE = ("Generated by tools/gen_apiary_stand_models.py -- regenerate, do not edit. {base}.json "
        "plus the stand: scaffolding_stable's own geometry, dropped a block, grown {skin} on each "
        "face and drawn in the hive's boards, so it covers the scaffolding rather than standing "
        "beside it. The body cubes are repeated because a child model's elements replace its "
        "parent's outright. Vanilla's cullfaces are dropped: they named scaffolding's block "
        "boundaries, which these faces are no longer on.")


def generate(out):
    for base, name in (("apiary", "apiary_stand"), ("apiary_bottom", "apiary_bottom_stand")):
        with open("%s/%s.json" % (out, base), encoding="utf-8") as f:
            body = json.load(f)

        model = {
            "__comment": NOTE.format(base=base, skin=SKIN),
            "parent": body["parent"],
            "textures": dict(body["textures"], post="mellifera:block/apiary_stand"),
            "elements": body["elements"] + STAND,
        }

        with open("%s/%s.json" % (out, name), "w", encoding="utf-8", newline="\n") as f:
            json.dump(model, f, indent=2)
            f.write("\n")

        print("%s/%s.json  %d elements (%d body + %d stand)"
              % (out, name, len(model["elements"]), len(body["elements"]), len(STAND)))


if __name__ == "__main__":
    generate(sys.argv[1] if len(sys.argv) > 1 else ".")
